### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by aryoow** [ItWasAllIntended/Steam-Comment-Bot#2]
Estimated time: 17.0 minutes
An error occured while commenting on 76561198338466762's profile with error code: The settings on this account do not allow you to add comments.
Make sure all your entered info is correct and the delay is sufficient
Finished

**Comment by ItWasAllIntended** [comment]
Either the account ID is wrong, your login details are wrong or you've not added that ID as a friend so you're limited to 5 comments. I've just realised I've not added this to the README, I'll make that more clear. Thanks
