### ISSUE TITLE
Trio cutom handler

### ISSUE THREAD

**Issue by perzsa** [ItWasAllIntended/Steam-Comment-Bot#3]
im getting this error,any solution?

/.local/lib/python3.6/site-packages/trio/_core/_multierror.py:472: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  category=RuntimeWarning
Estimated time: 6.7 minutes
Finished

**Comment by ItWasAllIntended** [comment]
Does this prevent function of the bot?
